### PR TITLE
WIP: Refactor lexer.

### PR DESCRIPTION
**Pull request by Ismael-VC**
This starts my work towards refactoring and documenting the lexer.

Reference: https://github.com/JuliaLang/JuliaParser.jl/issues/44

- [x] make all global consts all caps.
- [x] refactor closures
- [ ] document everything
- [ ] change cryptic names to more mnemonic and descriptive ones

### CODE REVIEW

**Comment by Ismael-VC** [comment]
Rebasing PR.

**Comment by Keno** [comment]
Please squash the commits

**Comment by tkelman** [comment]
the github auto squash has gotten better about concatenating commit messages, so it's totally usable now

**Comment by Keno** [comment]
Yes, but this would be easier to review if it was rebased and squashed.

**Comment by Ismael-VC** [comment]
@Keno I have rebased and squashed, sorry it took me so long.

**Comment by Keno** [comment]
Very nice cleanup, thank you!

**Pull request merged**
